language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit -c phpunit.xml --colors --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/coveralls -v
